import React, { Component } from 'react'
import Head from "next/head";

export default class success extends Component {
  render() {
    return (
        <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <Head>
            <title>GateKeeper</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="max-w-md w-full space-y-8">
            <div>
                <img
                className="mx-auto h-12 w-auto"
                src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
                alt="Workflow"
                />
                <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
                Welcome to GateKeeper
                </h2>
            </div>
            <div>
                <img
                    className="mx-auto h-48 w-auto"
                    src="https://www.svgrepo.com/show/13650/success.svg"
                    alt="Workflow"
                />
                <h2 className="mt-6 text-center text-xl font-extrabold text-gray-900">
                Access Approved
                </h2>
            </div>
            </div>
        </div>
    );
  }
}