import React, { Component } from "react";
import Head from "next/head";
import Image from "next/image";
import picture from "../public/gatekeeper.svg";

export default class success extends Component {
  render() {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
        <Head>
          <title>GateKeeper</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="max-w-md w-full space-y-8">
          <div className="text-center">
            <Image
              src={picture}
              alt="GateKeeper"
              width="200px"
              height="200px"
            />
          </div>
          <div>
            <h2 className="mb-6 text-center text-xl font-extrabold text-gray-900">
              Access Approved
            </h2>
            <img
              className="mx-auto h-48 w-auto"
              src="https://www.svgrepo.com/show/13650/success.svg"
              alt="Workflow"
            />
          </div>
        </div>
      </div>
    );
  }
}
